### PR TITLE
Fix timestamp format for all locales

### LINKED ISSUE #55: Timestamp formatting broken for various locales
With reference to #19 and #20, there are still issues with timestamping when the lib is being run e.g. on Swedish or German locale.
The offending line is:
https://github.com/splunk/splunk-library-dotnetlogging/blob/master/src/Splunk.Logging.Common/HttpEventCollectorEventInfo.cs#L179

It is:
`Timestamp = epochTime.ToString("#.000", Thread.CurrentThread.CurrentCulture);`
It should be:
`Timestamp = epochTime.ToString("#.000", System.Globalization.CultureInfo.InvariantCulture);`

I'm relaying this information for a colleague, I don't do any C/.NET developement myself.

### PR DESCRIPTION
**Pull request by fantavlik**
Resolve #55.

Fix timestamp format to use decimal points for all locales to be compatible with Splunk expected format.

Fix tests to ensure decimals being used for DE and US. DE and SE were previously failing due to the use of commas per issue #19. This was originally fixed in https://github.com/splunk/splunk-library-dotnetlogging/pull/20 but regression was introduced while adding tests.

Update testing matrix to target Splunk 8.0.2 and 7.3.4.

### CODE REVIEW

File: test/unit-tests/TestHttpEventCollector.cs [hunk 1]
```diff
@@ -718,17 +718,22 @@ public void HttpEventCollectorEventInfoTimestampsInvariantTest()
...
+                new HttpEventCollectorEventInfo(fixedTime.AddHours(-1), null, null, null, null, null);
+
+            // Make sure this format matches expected decimal format with three decimal places
+            Assert.Equal(eiDE.Timestamp, "1577833200.000");
 
             // Reset the culture before any assertions
             Thread.CurrentThread.CurrentCulture = backupCulture;
 
-            // Ensure we have a comma when using a non-US culture
-            Assert.True(ei.Timestamp.Contains(","));
```
Comment (fantavlik) [inline test/unit-tests/TestHttpEventCollector.cs]: I believe the original issue per #19 was that the timestamp DID contain a comma which Splunk rejected so this test was changed to confirm that a decimal point was used instead for both locales being tested.
